config/routes.rb
MoviesApp::Application.routes.draw do

  get "actors/index"
  # Home page
  root "movies#index"

  # Movie resource
  resources :movies
  resources :directors
  resources :actors

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_many :roles
  has_many :movies, :through => :roles

end

app/models/director.rb
class Director < ActiveRecord::Base

  has_many :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  belongs_to :director
  has_many :roles
  has_many :actors, through: :roles

  # def director
  #   Director.find_by(:id => self.director_id)
  # end

  # def roles
  #   Role.where(:movie_id => self.movie_id)
  # end

end

app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :movie
  belongs_to :actor

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all.order('name asc')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @directors = Director.all.order("name asc")
  end

  def show
    the_director_id = params["id"]
    @director = Director.find_by :id => the_director_id
  end

  def destroy
    the_director_id = params["id"]
    m = Director.find_by(:id => the_director_id)
    m.destroy
    redirect_to directors_url
  end

  def new
  end

  def create
    m = Director.new
    m.name = params["name"]
    m.photo_url = params["photo_url"]
    m.save
    redirect_to directors_url
  end

  def edit
    the_director_id = params["id"]
    @director = Director.find_by(:id => the_director_id)
  end

  def update
    the_director_id = params["id"]
    director = Director.find_by(:id => the_director_id)
    director.name = params["name"]
    director.photo_url = params["photo_url"]
    director.save
    redirect_to directors_url
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all.order("title asc")
  end

  def show
    the_movie_id = params["id"]
    @movie = Movie.find_by :id => the_movie_id
  end

  def destroy
    the_movie_id = params["id"]
    m = Movie.find_by(:id => the_movie_id)
    m.destroy
    redirect_to movies_url
  end

  def new
  end

  def create
    m = Movie.new
    m.title = params["title"]
    m.year = params["year"]
    m.plot = params["plot"]
    m.poster_url = params["poster_url"]
    m.director_id = params["director_id"]
    m.save
    redirect_to movies_url
  end

  def edit
    the_movie_id = params["id"]
    @movie = Movie.find_by(:id => the_movie_id)
  end

  def update
    the_movie_id = params["id"]
    movie = Movie.find_by(:id => the_movie_id)
    movie.title = params["title"]
    movie.year = params["year"]
    movie.plot = params["plot"]
    movie.director_id = params["director_id"]
    movie.poster_url = params["poster_url"]
    movie.save
    redirect_to movies_url
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<h1>Actors</h1>


<% @actors.each do |actor| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag actor.photo_url, :class => "col-md-10" %>
    </div>
    <div class="col-md-9">
      <h2><%= actor.name %></h2>

      <p class="lead"><%= actor.bio %></p>
    </div>
  </div>
<% end %>

app/views/directors/index.html.erb
<div class="page-header">

  <%= link_to "Add a New Director", new_director_path,
              :class => "pull-right btn btn-success btn-large" %>

  <h1>Directors</h1>
</div>

<% @directors.each do |director| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag director.photo_url, :class => "col-md-10" %>
    </div>
    <div class="col-md-9">
      <h2>
        <%= link_to director.name, '#' %>
      </h2>
      <p>
        <%= link_to "Edit This Director", '#' %> |
        <%= link_to "Delete This Director", '#', method: 'delete' %>
      </p>
      <% director.movies.each do |movie| %>
        <h3><%= movie.title %></h3>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MoviesApp</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.3/cerulean/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">


  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MovieFlix", "/", :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="/movies">Movies</a></li> -->
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to "Directors", directors_path %></li>
        <li><%= link_to "Actors", actors_path %></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/movies/edit.html.erb
<div class="page-header">
  <h1>Edit Movie</h1>
</div>

<div class="row">
  <div class="col-md-6">

    <%= form_tag "/movies/#{@movie.id}", :method => 'patch' do %>

      <div class="form-group">
        <%= label_tag :title %>
        <%= text_field_tag :title, @movie.title, class: 'form-control', placeholder: 'Enter movie title here' %>
      </div>

      <div class="form-group">
        <%= label_tag :director_id, "Director" %>
        <select name="director_id" class="form-control">
          <% Director.all.order('name asc').each do |director| %>
            <option value=<%= director.id %>
              <%= "selected" if @movie.director_id == director.id %>>
              <%= director.name %>
            </option>
          <% end %>
        </select>
      </div>

      <div class="form-group">
        <%= label_tag :poster_url %>
        <%= url_field_tag :poster_url, @movie.poster_url, class: 'form-control', placeholder: 'Enter URL to a movie poster image' %>
      </div>

      <div class="form-group">
        <%= label_tag :year %>
        <%= text_field_tag :year, @movie.year, class: 'form-control', placeholder: "Enter year here" %>
      </div>

      <div class="form-group">
        <label for="year">Plot Summary:</label>
        <textarea name="plot" class="form-control" id="year" placeholder="Enter plot here">
          <%= @movie.plot %>
        </textarea>
      </div>

      <%= submit_tag 'Update Movie', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/movies/index.html.erb
<div class="page-header">

  <%= link_to "Add a New Movie", "/movies/new",
              :class => "pull-right btn btn-success btn-large" %>

  <h1>Movies</h1>
</div>

<% @movies.each do |movie| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag movie.poster_url, :class => "col-md-10" %>
    </div>
    <div class="col-md-9">
      <h2>
        <%= link_to movie.title, movie_path(movie.id) %>
        (<%= movie.year %>)
      </h2>
      <p class="lead">
        <span class="label label-success"><%= movie.duration %> minutes</span>
      </p>
      <p class="lead"><%= movie.plot %></p>
      <p>Directed by <%= movie.director.name %></p>

      <p>Starring:</p>
      <% movie.actors.each do |actor| %>
        <% if actor.photo_url.present? %>
          <%= image_tag(actor.photo_url, size: "100", class: 'img-circle') %>
        <% end %>
      <% end %>
      <p>
        <%= link_to "Edit This Movie", edit_movie_path(movie.id) %> |
        <%= link_to "Delete This Movie", movie_path(movie.id), :method => 'delete' %>
      </p>
    </div>
  </div>
<% end %>

app/views/movies/new.html.erb
<div class="page-header">
  <h1>Add a New Movie</h1>
</div>

<div class="row">
  <div class="col-md-6">

    <%= form_tag movies_url, :method => 'post' do %>

      <div class="form-group">
        <%= label_tag :title %>
        <%= text_field_tag :title, "", class: 'form-control', placeholder: 'Enter movie title here' %>
      </div>

      <div class="form-group">
        <%= label_tag :director_id, "Director" %>
        <%= select_tag :director_id, options_from_collection_for_select(Director.all.order('name asc'), :id, :name), class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag :poster_url %>
        <%= url_field_tag :poster_url, "", class: 'form-control', placeholder: 'Enter URL to a movie poster image' %>
      </div>

      <div class="form-group">
        <%= label_tag :year %>
        <%= text_field_tag :year, "", class: 'form-control', placeholder: "Enter year here" %>
      </div>

      <div class="form-group">
        <label for="year">Plot Summary:</label>
        <input type="text" name="plot" class="form-control" id="year" placeholder="Enter year here" %>
      </div>

      <%= submit_tag 'Add Movie', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/movies/show.html.erb
<div class="page-header">
  <%= link_to "Edit This Movie", edit_movie_path(@movie.id), class: 'pull-right btn btn-large btn-info' %>
  <%= link_to "Delete This Movie", movie_path(@movie.id), method: 'delete', class: 'pull-right btn btn-large btn-danger' %>

  <h1><%= @movie.title %></h1>
</div>

<div class="row">
  <div class="col-md-3">
    <%= image_tag @movie.poster_url %>
  </div>
  <div class="col-md-9">
    <p class="lead">
      <strong>Title:</strong>
      <%= @movie.title %>
    </p>
    <p class="lead"><strong>Year: </strong><%= @movie.year %></p>
    <p class="lead"><strong>Plot: </strong><%= @movie.plot %></p>
    <p class="lead"><strong>Director: </strong><em>Director goes here</em></p>
    <p class="lead"><strong>Cast: </strong><em>Cast goes here</em></p>
  </div>
</div>